services:
  app:
    container_name: passm
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    ports:
      - "3200:3200"   # ggf. anpassen, falls deine App einen anderen Port nutzt
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./data:/app/data   # optional, falls deine App Daten speichert
